### Get all fastest laps
GET http://localhost:5074/api/FastestLapApi
Accept: application/json

###
### Create a new cartyre
POST http://localhost:5074/api/TyreApi/AddTyreToCar HTTP/1.1
Content-Type: application/json

{
  "carId": 4,
  "tyre": "Soft",
  "tyrePressure": 21,
  "operationalTemperature": 85
}

