# @no-redirect
# @no-cookie-jar
POST http://localhost:5074/api/TyreApi/AddTyreToCar
Accept: application/json
Content-Type: application/json

{
  "CarId": 4,
  "Tyre": "Soft",
  "TyrePressure": 40,
  "OperationalTemperature": 120
}
###


# @no-redirect
# @no-cookie-jar
POST http://localhost:5074/api/TyreApi/AddTyreToCar
Accept: application/json
Content-Type: application/json
Cookie: .AspNetCore.Identity.Application=CfDJ8MZ--MWX5KpPlOsqQRVzADwc_-CAJW_GsdGhSUbPWX_CgUO2-GZQ33inPTsnjqrQLbbpIqs3E6TgZldJ_e8aNlRXZOS4QSyC-DZEhGSmD1zpLBKfySjrD3C-wdhwriTU-nxG2D4qOxtPwwXXta90WkdsDq1H6HnVQj05jadOlYC0eGfKJQJfqWhsAJWb5U8XGW-Gu735lBj5mEqpOc9TFUik_PVzjS33nONM5xEFog3xr8sHZjIBKDx580Lq-6OEnwT-QbsrZO2DqDxuTyfjexCaEsq5szR_oHmOt6mD2moxAAvnCeGCbHLv6SG-d7n62KQ0AUzDEJdmDK8zQmkxMAfYBQ8QhMYBM6_pqnxHP8Yh6jBsEJhJdA1PH095INREnJ3JhD1tn734GgvnwTjauvOgm779Hx6Nl39BzIuLQhJPsCodjJwsY4e6ctsrfKGm9alged6xYAM3f7FLQNCn8jyyy6iz-4MtYsa_8LpK8-4AA6I08lnbrICFwwwbDm-fEKe3q1C_LxPKXlI6zU8xTM33WJ42hQ-k6g8XTzCjfx23HZ7mG1f02_b5O4WR9N6FxXRlzgs3Jg2CFtnLu59YursPhv6nRxrKdzttxUzZRHMdqoYFuFr3dsm59k1x_1mtli9GADUq4dmaADKxBOqc7coTKxsjn6PkKO2Nbl6T3sbfHbltA9yqZHjYx9ceHuNsvU9MGMe6rS0pYGmuH2ub9v56NZ-npfpU0ej6_-BDQkH1P5IzgoLMDnruZAaFGIk-mVhRrGt2JVduDCs7Ye9fIusA_aklDCcA2z9kjbT8Pjnpv3XZBXh9EwEq185bZcpu6w
Cookie: .AspNetCore.Antiforgery.xPQZ6ly-kNk=CfDJ8MZ--MWX5KpPlOsqQRVzADxR__OVk5s6Ef0etiLGj1zWM_yEoXDyS3XiSoKn02kOnelHY8wob4O3CtSkGX1vZurqwhzBl6oW0wTvMOl0iDc9lSaK4YPAEcN8zBz4fL8g0ADK1idnRdaDHZNnbGJDZGo

{
  "CarId": 4,
  "Tyre": "Soft",
  "TyrePressure": 40,
  "OperationalTemperature": 120
}
###




