image: mcr.microsoft.com/dotnet/sdk:8.0

stages:
  - build
  - test
  - coverage_report

cache:
  key: dotnet-cache
  paths:
    - .nuget  # Cache NuGet dependencies for faster builds

before_script:
  - dotnet --version  # Verify .NET SDK version

build:
  stage: build
  script:
    - dotnet restore  # Restore dependencies
    - dotnet build --configuration Release  # Build the project
  artifacts:
    paths:
      - "**/bin/Release/net8.0/"  # Store compiled binaries
    expire_in: 1 hour

tests:
  stage: test
  script:
    - 'dotnet test Tests/Tests.csproj --logger junit --collect:"XPlat Code Coverage"'
    - 'dotnet tool install dotnet-reportgenerator-globaltool --version 5.4.4 --tool-path tools'
    - './tools/reportgenerator -reports:"Tests/TestResults/*/coverage.cobertura.xml" -targetdir:"Tests/coveragereport" -reporttypes:"Html"'
  artifacts:
    reports:
      junit: Tests/TestResults/TestResults.xml  # Store test results in GitLab
    paths:
        - Tests/coveragereport
    expire_in: 1 day