image: gradle:7.4.2-jdk11  # Gradle + Java 11

stages:
  - build
  - test

cache:
  paths:
    - .gradle/wrapper/
    - .gradle/caches/

build:
  stage: build
  script:
    - gradle build
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 hour

unit_tests:
  stage: test
  script:
    - gradle test
  artifacts:
    reports:
      junit: build/test-results/test/*.xml  # Testresultaten tonen in GitLab UI
    expire_in: 1 day

coverage_report:
  stage: test
  script:
    - gradle jacocoTestReport
    - mkdir -p coverage
    - cp -r build/reports/jacoco/test/html/* coverage/
  artifacts:
    paths:
      - coverage/
    expire_in: 1 week
