image: mcr.microsoft.com/dotnet/sdk:8.0

stages:
  - build
  - test
  - coverage_report

cache:
  key: dotnet-cache
  paths:
    - ~/.nuget/packages  # Cache NuGet dependencies for faster builds

before_script:
  - dotnet --version  # Verify .NET SDK version

build:
  stage: build
  script:
    - dotnet restore  # Restore dependencies
    - dotnet build --configuration Release  # Build the project
  artifacts:
    paths:
      - "**/bin/Release/net7.0/"  # Store compiled binaries
    expire_in: 1 hour

unit_tests:
  stage: test
  script:
    - dotnet test Tests/Tests.csproj --logger "trx;LogFileName=test-results.trx" --results-directory ./TestResults/
  artifacts:
    reports:
      junit: ./TestResults/test-results.trx  # Store test results in GitLab
    expire_in: 1 day

integration_tests:
  stage: test
  script:
    - dotnet test Tests/Tests.csproj --filter "Category=Integration" --logger "trx;LogFileName=integration-test-results.trx" --results-directory ./TestResults/
  artifacts:
    reports:
      junit: ./TestResults/integration-test-results.trx  # Store integration test reports
    expire_in: 1 day

coverage_report:
  stage: coverage_report
  script:
    - dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=lcov
    - mkdir -p coverage
    - cp -r Tests/TestResults/* coverage/  # Copy coverage reports
  artifacts:
    paths:
      - coverage/
    expire_in: 1 week
