stages:
  - setup
  - build
  - test

setup:
  stage: setup
  script:
    - apt-get update && apt-get install -y wget unzip
    - wget https://dlcdn.apache.org/maven/maven-3/3.8.6/binaries/apache-maven-3.8.6-bin.zip
    - unzip apache-maven-3.8.6-bin.zip
    - mv apache-maven-3.8.6 /opt/maven
    - echo "export PATH=/opt/maven/bin:$PATH" >> ~/.bashrc
    - source ~/.bashrc
    - mvn -version  # Controleer installatie

build:
  stage: build
  script:
    - mvn clean package
  artifacts:
    paths:
      - target/*.jar
    expire_in: 1 hour
